### ISSUE TITLE
ревью

### ISSUE THREAD

**Issue by HukakHePak** [rusbers/Storage#1]
привет, могу поревьюить, если не против

**Comment by rusbers** [comment]
Привет, не против

**Comment by HukakHePak** [comment]
Уже поздновато конечно, в стриме много чего интересного сказали. Но тем не менее

Поле класса this.value не совсем имеет смысл. Просто дублирует то, что уже находится в localStorage (sessionStorage). Можно просто оставить this.set(value). Не знаю в чем преимущество прописать везде привязки и написать методам static, но вроде и без этого все отлично работает. ну про тернарный return true : false уже сказали, что это не имеет смысла. Потом, в некоторых функциях постоянно дублируется код с разницей лишь в типе storage (local/session) раз уж пошло, может сделать еще одну функцию, которая бы делала все эти привязки и просто отправлять в нее нужный тип хранилища? Пока писал уже начало казаться, что это шутка какая-то

**Comment by rusbers** [comment]
Соглашусь что написал много лишнего, но это осознанно потому что задача была очень легкой и я хотел немного поэкспериментировать. 

То что я использовал статик это потому что я просто хотел потренироваться в использовании методов bind, call и apply. Ничего большего)

В целом, да, весь код это был эксперимент и поэтому много чего тут может показаться шуткой.

Спасибо за ревью

**Comment by HukakHePak** [comment]
да да, я ток потом подумал, что это тренировка
